version: '3.8'

services:

  mongoserver:
    build: 
      context: ./../mongoService
      dockerfile: ./../mongoService/mongo.dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
    depends_on:
      - mongodb
    deploy:
      mode: replicated
      replicas: 1

  postgreserver:
    build: 
      context: ./../postgresService
      dockerfile: ./../postgresService/postgres.dockerfile
    restart: always
    ports:
      - "8082:8082"
    environment:
      POSTGRES_URI: "postgresql://vijay:12345@postgres:5432/users?sslmode=disable"
    depends_on:
      - postgres
  mongodb:
    image: mongo
    container_name: mongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=vijay
    #   - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - "27017:27017"
    restart: always
    # volumes:
    #   - './mongo:/data/db'  

  postgres:
    image: 'postgres:14.2'
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: vijay
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data  

