version: '3.8'

services:

  mongoserver:
    build: 
      context: ./../mongoService
      dockerfile: ./../mongoService/mongo.dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      TEST_T: "Testing env"
    depends_on:
      - mongodb


  mongodb:
    image: mongo
    container_name: mongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=vijay
    #   - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - "27017:27017"
    restart: always
    # volumes:
    #   - './mongo:/data/db'  
      