version: '3.8'

services:

  frontend:
    build: 
      context: ./../frontEndService
      dockerfile: ./../frontEndService/front.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  mongoserver:
    build: 
      context: ./../mongoService
      dockerfile: ./../mongoService/mongo.dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
      DB_NAME: "microservices"
      COLLECTION_NAME: "users"
    depends_on:
      - mongodb
    deploy:
      mode: replicated
      replicas: 1

  postgreserver:
    build: 
      context: ./../postgresService
      dockerfile: ./../postgresService/postgres.dockerfile
    restart: always
    ports:
      - "8082:8082"
    environment:
      POSTGRES_URI: "postgresql://vijay:12345@postgres:5432/users?sslmode=disable"
      # POSTGRES_URI: "host=postgres port=5432 user=vijay password=12345 dbname=users sslmode=disable timezone=UTC connection_timeout=10"
    depends_on:
      - postgres


  mongodb:
    image: mongo
    container_name: mongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=vijay
    #   - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - "27017:27017"
    restart: always
    # volumes:
    #   - './mongo:/data/db'  

  postgres:
    image: 'postgres:14.2'
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: vijay
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql  

